### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by FireController1847** [TooTallNate/iheart#1]
I feel like I misunderstand how to use this module, but all I know is when requiring it in node.js it doesn't work xD
```js
/node_modules/iheart/index.js:1
(function (exports, require, module, __filename, __dirname) { import { extname } from 'path'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at eval (eval at execute (/home/firecontroller1847/discord-bots/pandora-v7/src/commands/Owner/eval.js:15:42), <anonymous>:1:16)
```

**Comment by TooTallNate** [comment]
Please try v3.0.0. I removed the ES6 Modules stuff in favor of regular `module.exports`.

**Comment by FireController1847** [comment]
Doing that has fixed it, thanks!
